---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create containers
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        recreate: false
        privileged: "{{ item.privileged | default(false) }}"
        cgroupns_mode: "{{ item.cgroupns | default(private) }}"
        volumes: "{{ item.volumes | default(omit) }}"
      loop: "{{ molecule_yml.platforms }}"
