---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: debian-vector
    image: docker.io/geerlingguy/docker-debian11-ansible
    hostname: debian-vector
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns: host
    command: "/lib/systemd/systemd"
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      deprecation_warnings: False
      interpreter_python: auto_silent
  env:
    ANSIBLE_PIPELINING: "True"
    ANSIBLE_ROLES_PATH: /opt/

verifier:
  name: ansible

scenario:
  test_sequence:
    - create
    - converge
    - verify
    - destroy